// --- TEHTÄVÄKIRJASTO ---
const defaultTasks = [
    { id: 1, n: "Mise en place", d: "Varmista, että kaikilla pöytäseurueen jäsenillä on lasissa juotavaa (myös vettä). Jos jollain on tyhjää, täytä lasia omalla juomallasi tai vedellä.", p: 2, m: 2, b: false, r: 2, k: 'juoma' },
    { id: 2, n: "Uudelleenkäynnistys (Reboot)", d: "Kaikkien suorittajien on juotava lasi vettä yhdeltä istumalta 'järjestelmän vakauttamiseksi'.", p: 1, m: 3, b: false, r: 3, k: 'juoma' },
    { id: 3, n: "Holari-yritys", d: "Heitä lasinalunen tyhjään tuoppiin tai lasiin 2 metrin etäisyydeltä. Kolme yritystä.", p: 2, m: 2, b: false, r: 2, k: 'liikunta' },
    { id: 4, n: "Air Drop saapuu", d: "Tilaa valitsemallesi pelaajalle juoma (mieto tai alkoholiton käy).", p: 3, m: 1, b: false, r: 1, k: 'juoma' }, 
    { id: 5, n: "Gordon Ramsay -palautekierros", d: "Kehu nykyisen baarin miljöötä tai juomavalikoimaa yhdelle tuntemattomalle asiakkaalle 'ammattilaisen otteella'.", p: 2, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 6, n: "Tikettijärjestelmän ruuhka", d: "Kuuntele valitsemasi pelaajan yksi valitsema muisto tai ongelma menneisyydestä keskeyttämättä. Lopuksi analysoi 'ratkaisu'.", p: 1, m: 2, b: false, r: 2, k: 'pokka' }, 
    { id: 7, n: "Spotterin rooli", d: "Seuraa oikealla puolellasi istuvan pelaajan lasia 5 minuutin ajan. Jos hän aikoo laskea sen pöydälle ilman alusta, estä se tai aseta alunen alle.", p: 2, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 8, n: "Level 3 -kypärä", d: "Pidä mukanasi jotain outoa esinettä (esim. tyhjä tölkki tai pilli) seuraavaan baariin asti hukkaamatta sitä.", p: 2, m: 2, b: false, r: 2, k: 'liikunta' },
    { id: 9, n: "Uunilohi palaa pohjaan", d: "Suorittajien on poistuttava välittömästi ulos 'tuulettumaan' 2 minuutiksi ilman puhelimia.", p: 1, m: 4, b: false, r: 4, k: 'liikunta' },
    { id: 10, n: "BIOS-päivitys", d: "Kerro vasemmalla puolellasi istuvalle pelaajalle yksi asia, jota hän ei vielä tiennyt sinusta (IT-salaisuus).", p: 1, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 11, n: "Caddy-palvelu", d: "Kanna valitsemasi pelaajan takkia tai laukkua seuraavaan siirtymään (tai baarin sisällä siirtyessä).", p: 2, m: 1, b: false, r: 1, k: 'liikunta' }, 
    { id: 12, n: "Pochinki Loot", d: "Hae koko seurueelle nippu ilmaisia servettejä tai pillejä tiskiltä ja jaa ne. Esineen saajan on kannettava sitä mukana seuraavaan baariin saakka tai tulee -1 xp.", p: 1, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 14, n: "Palomuuri (Firewall)", d: "Seiso valitsemasi toisen pelaajan ja muiden asiakkaiden välissä 'suojana' 3 minuutin ajan.", p: 2, m: 2, b: false, r: 2, k: 'pokka' },
    { id: 15, n: "OB-linja (Out of Bounds)", d: "Käy koskettamassa baarin kaukaisinta seinää ja palaa takaisin sanomatta sanaakaan matkalla.", p: 1, m: 3, b: false, r: 3, k: 'liikunta' },
    { id: 16, n: "Red Zone", d: "Kukaan suorittajista ei saa käyttää sanaa 'joo' tai 'ei' seuraavan 5 minuutin aikana.", p: 2, m: 5, b: false, r: 5, k: 'pokka' },
    { id: 18, n: "Ping-testi", d: "Heitä yläfemma kaikkien muiden seurueen jäsenten kanssa mahdollisimman nopeasti (alle 10 sekuntia).", p: 1, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 19, n: "Mandatory-kierto", d: "Nouse ylös! Ennen kuin istut alas, sinun on kierrettävä valittu pöytä tai tuoli myötäpäivään ympäri.", p: 1, m: 4, b: false, r: 4, k: 'liikunta' },
    { id: 22, n: "Etätuki-istunto", d: "Selitä toiselle pelaajalle mahdollisimman monimutkaisesti, miten jokin arkipäiväinen esine (esim. kynä) toimii.", p: 1, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 23, n: "Putterin tarkkuus", d: "Liu'uta lasi pöytää pitkin mahdollisimman lähelle reunaa tippumatta. Kolme yritystä.", p: 2, m: 2, b: false, r: 2, k: 'liikunta' },
    { id: 24, n: "Med Kit -huolto", d: "Hae synttärisankarille lasi vettä.", p: 3, m: 1, b: true, r: 1, k: 'juoma' }, 
    { id: 26, n: "Käyttäjävirhe (User Error)", d: "Sano 'Olen pahoillani, kyseessä oli käyttäjävirhe' aina kun joku seurueesta tekee jotain kömpelöä seuraavan 10 min aikana.", p: 2, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 27, n: "Fore!", d: "Huuda 'FORE!' (kohtuullisella volyymilla) aina kun joku seurueesta nousee seisomaan. Kesto 5 minuuttia.", p: 1, m: 2, b: false, r: 2, k: 'pokka' },
    { id: 28, n: "Blue Zone -siirtymä", d: "Seuraavaan baariin siirryttäessä suorittajien on kuljettava viimeisenä ja varmistettava, ettei ketään jää jälkeen.", p: 1, m: 2, b: false, r: 2, k: 'liikunta' },
    { id: 29, n: "Raaka-aineanalyysi", d: "Tunnista sokkona (silmät kiinni) mitä juomaa oikealla istuvan pelaajan lasissa on hajun perusteella.", p: 2, m: 1, b: false, r: 1, k: 'juoma' },
    { id: 32, n: "Winner Winner Chicken Dinner", d: "Nouse ylös, tuuleta näyttävästi ja esitä syöväsi voiton kunniaksi kuvitteellista kana-ateriaa. Huuda lopuksi 'Winner Winner Chicken Dinner!'", p: 3, m: 1, b: false, r: 1, k: 'pokka' }, 
    { id: 35, n: "Red Zone Survival", d: "Kyykisty pöydän alle suojaan 30 sekunniksi välittömästi, kun joku huutaa 'POMMI!'.", p: 1, m: 1, b: false, r: 3, k: 'liikunta' },
    { id: 36, n: "Pro-tason draiveri", d: "Heitä roskasi (esim. karkkipaperi tai kuitti) roskikseen vähintään 3 metrin päästä. Onnistuttava!", p: 2, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 37, n: "Tukipyyntö (Support Ticket)", d: "Käy kysymässä baarimikolta: 'Voitteko auttaa, minulla on yhteysongelma?'", p: 3, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 38, n: "Salasanan vaihto", d: "Keksi vasemmalla istuvalle pelaajalle uusi lempinimi, jota kaikkien on käytettävä seuraavat 10 minuuttia.", p: 2, m: 1, b: false, r: 1, k: 'pokka' }, 
    { id: 39, n: "UAV aktivoitu", d: "Käy tarkistamassa onko baarin toisessa huoneessa tai tiskillä tilaa ja raportoi takaisin.", p: 1, m: 0, b: false, r: 1, k: 'liikunta' },
    { id: 40, n: "Kiekon etsintä", d: "Etsi baarin lattialta tai pöytien alta jokin pudonnut esine ja palauta se omistajalle.", p: 1, m: 1, b: false, r: 2, k: 'liikunta' },
    { id: 41, n: "Sous-viden lämpö", d: "Hiero valitsemasi pelaajan hartioita 1 minuutin ajan 'lämmittääksesi' hänet seuraavaan baariin.", p: 1, m: 0, b: false, r: 1, k: 'pokka' }, 
    { id: 43, n: "Bridge Camping", d: "Seiso baarin oviaukon tai kapean kohdan lähellä 2 minuuttia 'vartioimassa' kulkua.", p: 2, m: 1, b: false, r: 2, k: 'pokka' },
    { id: 44, n: "Levyaseman virhe", d: "Vaihda kenkiäsi päittäin (vasen oikeaan ja oikea vasempaan) 5 minuutin ajaksi.", p: 2, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 45, n: "Ping-mittaus", d: "Tökkää sormella viereisiä pelaajia olkapäähän ja sano 'Ping' aina kun he ottavat kulauksen juomastaan.", p: 1, m: 0, b: false, r: 1, k: 'pokka' }, 
    { id: 46, n: "Ethernet-kaapeli", d: "Muodosta 'yhteys' pitämällä kädestä kiinni naapuria 3 minuutin ajan keskeytyksettä.", p: 1, m: 1, b: false, r: 3, k: 'liikunta' },
    { id: 48, n: "Flippaava kiekko", d: "Pyörähdä 360 astetta paikallasi kerran aina kun joku seurueesta katsoo puhelintaan.", p: 2, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 49, n: "Salty Player", d: "Kerro jokin asia, joka sinua ärsyttää (IT-ongelma tai huono grippi) erittäin intohimoisesti.", p: 1, m: 0, b: false, r: 1, k: 'pokka' },
    { id: 50, n: "Zonen reunalla", d: "Siirrä tuolisi niin kauas pöydästä kuin mahdollista ja yritä silti pysyä keskustelussa.", p: 2, m: 1, b: false, r: 2, k: 'liikunta' },
    { id: 52, n: "Komentorivi (CLI)", d: "Puhu seuraavat 3 minuuttia käyttäen vain yhden sanan lauseita. Esim. 'Jano. Juon. Nyt.'", p: 2, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 53, n: "Ace-tuuletus", d: "Juokse baarin ympäri (tai lyhyt lenkki) kädet levällään kuin olisit tehnyt hole-in-onen.", p: 3, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 55, n: "Lagipiikki", d: "Nouse ylös! Liiku nykien lagisesti kun tulet takaisin istumaan.", p: 2, m: 1, b: false, r: 2, k: 'liikunta' },
    { id: 56, n: "Fore!-varoitus", d: "Aina kun joku laskee lasin pöytään, huuda 'FORE!' seuraavan 5 minuutin ajan.", p: 1, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 57, n: "Lootbox-yllätys", d: "Käy ostamasta valitsemallesi pelaajalle jokin yllätys tiskiltä (pähkinöitä, tikkarit, tms).", p: 3, m: 0, b: false, r: 1, k: 'juoma' }, 
    { id: 58, n: "Stack Overflow", d: "Pinoa 3 tyhjää lasia päällekkäin ja pidä ne pystyssä 1 minuutti.", p: 1, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 59, n: "Putti-putki", d: "Heitä kolikko tai korkki lasiin metrin päästä. Onnistuttava kerran kolmesta.", p: 2, m: 1, b: false, r: 2, k: 'liikunta' },
    { id: 60, n: "Uunilohi-muisto", d: "Kerro nolo tai hauska muisto ammattikoulun ajoilta. Jos et muista, juo lasi vettä.", p: 1, m: 0, b: false, r: 1, k: 'pokka' },
    { id: 61, n: "Hardware Reset", d: "Kosketa varpaitasi polvia koukistamatta 15 sekuntia putkeen.", p: 1, m: 1, b: false, r: 2, k: 'liikunta' },
    { id: 62, n: "Ghillie-shotti", d: "Ota huikka juomastasi niin, että yrität olla mahdollisimman näkymätön (esim. takin alla).", p: 1, m: 1, b: false, r: 2, k: 'juoma' },
    { id: 63, n: "Ob-raja (Out of Bounds)", d: "Seuraavan siirtymän aikana et saa astua katuvalojen varjoihin (tai tiettyihin laattoihin).", p: 2, m: 1, b: false, r: 3, k: 'liikunta' },
    { id: 64, n: "Etätuki-puhelu", d: "Soita (tai teeskentele soittavasi) kaverille ja selitä miten baarijakkara 'asennetaan'.", p: 2, m: 1, b: false, r: 1, k: 'pokka' },
    { id: 65, n: "Drop-alueen vartija", d: "Pidä kättäsi toisen pelaajan tuolin selkänojalla 5 minuuttia 'suojellen häntä'.", p: 1, m: 1, b: false, r: 1, k: 'pokka' }, 
    { id: 66, n: "Caddy-vinkki", d: "Suosittele toiselle pelaajalle seuraavaa liikettä tai juomaa 'ammattilaisen varmuudella'.", p: 1, m: 0, b: false, r: 1, k: 'pokka' }, 
    { id: 67, n: "System Restore", d: "Istu täysin hiljaa ja silmät kiinni 30 sekuntia, kunnes 'boottaus' on valmis.", p: 1, m: 1, b: false, r: 2, k: 'pokka' },
    { id: 68, n: "Pan-haaste", d: "Pitele juomaasi kaksin käsin kuin se olisi painava paistinpannu seuraavat 5 minuuttia.", p: 1, m: 1, b: false, r: 1, k: 'liikunta' },
    { id: 69, n: "Ankkurilinkki", d: "Pidä jalkaasi toisen pelaajan jalan päällä seuraavan 3 minuutin ajan.", p: 1, m: 1, b: false, r: 2, k: 'liikunta' },
    { id: 71, n: "Scramble-peli", d: "Kaikki suorittajat vaihtavat paikkoja keskenään mahdollisimman nopeasti (juosten).", p: 1, m: 1, b: false, r: 4, k: 'liikunta' },
    { id: 72, n: "Bugiraportti", d: "Luettele 5 asiaa, jotka ovat 'vialla' nykyisessä sijainnissasi (vitsillä).", p: 1, m: 0, b: false, r: 1, k: 'pokka' },
    { id: 73, n: "Air Drop -paketti", d: "Nosta valitsemasi pelaajan juoma ilmaan ja huuda: 'Paketti toimitettu!' aina kun hän aikoo juoda.", p: 2, m: 1, b: false, r: 1, k: 'pokka' }, 
    { id: 74, n: "Spotterin silmät", d: "Kuvaile muille pelaajille, mitä tapahtuu oikealla istuvan pelaajan selän takana ilman että hän kääntyy.", p: 1, m: 0, b: false, r: 1, k: 'pokka' }, 
    { id: 76, n: "Frisbee-ketjut", d: "Kilistä lasiasi jonkun toisen pelaajan lasin reunaan ja huuda 'Ketjuihin!' aina kun hän ottaa ensimmäisen huikan uudesta juomasta.", p: 1, m: 1, b: false, r: 1, k: 'juoma' },
    { id: 78, n: "Keittiömestarin tarkastus", d: "Maista (luvan kanssa) pienen pieni pala jonkun ruuasta tai tilkkanen juomasta ja anna arvosana.", p: 1, m: 0, b: false, r: 2, k: 'juoma' },
    { id: 79, n: "Full Auto -sarja", d: "Juo 5 pientä hörppyä juomaasi peräkkäin 'sarjatulella'.", p: 1, m: 0, b: false, r: 2, k: 'juoma' },
    { id: 80, n: "Kiekon palautus", d: "Käy viemässä tyhjä lasi tiskille (itse valitsemasi) mahdollisimman tyylikkäästi.", p: 1, m: 0, b: false, r: 1, k: 'liikunta' },
    { id: 81, n: "Admin-komento", d: "Valitsemasi pelaaja joutuu kertomaan vitsin tai juomaan lasin vettä.", p: 2, m: 0, b: false, r: 2, k: 'pokka' }, 
    { id: 82, n: "Victory Dance", d: "Tee lyhyt ja energinen voittotanssi baarin lattialla (PUBG tyyliin).", p: 3, m: 1, b: false, r: 1, k: 'pokka' },
    
    { id: 103, n: "Palvelimen hätätuuletus", d: "Jos näet sytytetyn kynttilän, sammuta se heiluttamalla paperia tai servettiä, jota pidät huulien välissä.", p: 3, m: true, b: false, r: 1, k: 'liikunta' },
    { id: 104, n: "Valkokastikkeen pohja", d: "Tilaa lasi maitoa tai kermaa (kermasta GM antaa extra pisteen). Jos juot lasin tyhjäksi saat 1 extra pisteen.", p: 1, m: true, b: false, r: 1, k: 'juoma' },
    { id: 105, n: "Hylätty Dacia", d: "Ota selfie likaisimman auton kanssa mitä löydät.", p: 1, m: true, b: false, r: 1, k: 'liikunta' },
    { id: 106, n: "Random Squad -voicechat", d: "Puhu seuraavassa baarissa ainoastaan jotain muuta kieltä kuin suomea tai englantia.", p: 3, m: true, b: false, r: 1, k: 'pokka' },
    { id: 107, n: "Hole-in-one -hype", d: "Hypetä jonkun juomatilausta minuutin ajan (jos random GM antaa extra 2 pistettä).", p: 1, m: true, b: false, r: 1, k: 'pokka' },
    { id: 108, n: "Mystery Box -haaste", d: "Suunnitelkaa ryhmäcocktail ilman että kukaan tietää cocktailin muita ainesosia kuin omansa ja tilatkaa jokaiselle kyseinen cocktail. Juomalle täytyy antaa nimi ja ryhmän tulee ottaa kuva juoman kanssa.", p: 1, m: false, b: false, r: 3, k: 'juoma' },
    { id: 109, n: "Etätyöpöytä (Remote Desktop)", d: "Seuraavassa baarissa et saa itse juoda, jonkun täytyy juottaa sinua (jos random GM antaa extra 2 pistettä).", p: 2, m: true, b: false, r: 1, k: 'juoma' },
    { id: 110, n: "Laajakaistan maksimointi", d: "Juo juoma käyttämällä vähintään viittä pilliä samaan aikaan.", p: 1, m: true, b: false, r: 1, k: 'juoma' },
    { id: 111, n: "Tasting-lusikka", d: "Juo juoma käyttämällä lusikkaa.", p: 3, m: true, b: false, r: 1, k: 'juoma' },

    { id: 112, n: "Flashbang-tuijotuskisa", d: "Pelaajat ottavat mittaa toisistaan tuijotuskisassa. Se, joka räpäyttää silmiään, kääntää katseensa tai nauraa ensin, on häviäjä.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 113, n: "DDoS-hyökkäys", d: "GM antaa pitkän ja vaikean sanan tai lauseen. Kilpailijoiden pitää kirjoittaa se ryhmän WhatsAppiin/chattiin. Ensimmäisenä täysin virheettömän viestin lähettänyt voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 114, n: "Sudden Death -puttikisa", d: "Kumpikin heittää vuorotellen lasinalusta pystyssä olevaan tyhjään tuoppiin n. 2 metrin päästä. Heitetään 3 heittoa per pelaaja. Se, joka saa enemmän 'putteja' sisään, voittaa.", p: 3, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 115, n: "Tulinen Michelin-haaste", d: "Klassinen Kivi-paperi-sakset, mutta paras kolmesta -periaatteella (eli kaksi voittoa vaaditaan). Häviäjä joutuu ottamaan rankkumiinukset.", p: 1, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 116, n: "Medkit Speedrun", d: "Kummallakin on edessään saman kokoinen lasi vettä. Kun GM antaa luvan, ensimmäinen, joka juo vesilasinsa täysin tyhjäksi, voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 117, n: "Hardware-testi / Peukalopaini", d: "Klassinen peukalopaini! Ensimmäinen, joka saa painettua vastustajan peukalon kiinni nyrkkiin 3 sekunnin ajaksi, voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 118, n: "Loot Drop -sprintti", d: "GM huutaa jonkin yleisen baariesineen (esim. 'punainen pilli', 'karkkipaperi'). Ensimmäinen, joka juoksee hakemaan kyseisen esineen ja tuo sen GM:lle, voittaa.", p: 3, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 119, n: "Salasanan purku", d: "Puhdas arvauskilpailu. GM keksii numeron 1-100 väliltä ja kirjoittaa sen ylös. Kumpikin pelaaja arvaa numeron kerran ääneen. Se, kenen arvaus on lähempänä, voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 120, n: "CTP-kisa (Closest to Pin)", d: "Kumpikin liu'uttaa kolikon tai lasinalusen pöydän vastakkaista reunaa kohti. Se, kenen esine pysähtyy lähimmäksi reunaa tippumatta, voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 121, n: "Sokkomaistelu", d: "Kummankin silmät laitetaan kiinni. GM antaa heidän haistaa tai maistaa pienen tipan jotain pöydästä löytyvää (esim. ketsuppi, suola, tietty juoma). Ensimmäinen oikein arvannut voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 122, n: "Salauksen purku", d: "GM keksii 3 sanaa ja lausuu ne takaperin (esim. 'I-RAAB' = baari). Ensimmäinen kilpailijoista, joka huutaa sanan oikein päin, saa pisteen. Paras kolmesta voittaa.", p: 3, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 123, n: "Quickscope-reaktio", d: "Kummankin kädet ovat selän takana. GM asettaa kolikon pöydälle. Kun GM sanoo 'TULI!', ensimmäinen joka iskee kätensä pöydälle kolikon päälle, voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 124, n: "Hankala Stanssi", d: "Tasapainokisa! Kumpikin seisoo yhdellä jalalla silmät kiinni. Ensimmäinen, joka horjahtaa, koskettaa maata toisella jalalla tai avaa silmät, häviää.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 125, n: "Keittiöapulaisen nopeustesti", d: "Taittohaaste! Molemmat saavat 3 servettiä. Ensimmäinen, joka on taitellut kaikki kolme siististi kolmioiksi ja huutaa 'VALMIS!', voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 126, n: "Tiedonhaku-protokolla Ctrl+F", d: "Googlauskisa. GM kysyy jonkin oudon triviakysymyksen. Ensimmäinen, joka löytää tiedon puhelimellaan ja huutaa vastauksen, voittaa.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 127, n: "Blue Zone -happikisa", d: "Hengityksen pidätys. Kun GM antaa merkin, molemmat vetävät keuhkot täyteen ja pidättävät hengitystä. Se kuka joutuu puhaltamaan ilmaa ulos ensin, häviää.", p: 3, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 128, n: "Vastatuuli-draivi", d: "Ilmakiekkoa! Pöydän keskelle laitetaan mytätty karkkipaperi. Kun aika alkaa, molemmat puhaltavat paperia kohti vastustajaa. Se, kenen syliin tai ohi paperi tippuu, häviää.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 129, n: "Masterchefin makupaletti", d: "Sanakilpailu. GM antaa raaka-aineen (esim. 'Peruna'). Kilpailijat sanovat vuorotellen ruokalajeja, joissa on tuota raaka-ainetta. Se kumpi miettii yli 3 sekuntia tai toistaa saman, häviää.", p: 2, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 130, n: "Ping-viive", d: "Laskentakisa. Kilpailijoiden pitää vuorotellen laskea taaksepäin sadasta alaspäin miinus seitsemän (100, 93, 86...). Ensimmäinen, joka sekoaa laskuissa tai miettii yli 3 sekuntia, häviää.", p: 3, m: true, b: false, r: 2, k: 'kilpailu' },
    { id: 131, n: "Tarkka-ampujan vakaus", d: "Kumpikin ottaa oman juomalasinsa ja nostaa sen suoralla kädellä eteensä ilmaan. Se, kenen käsi alkaa täristä liikaa, laskee alas tai koukistuu ensin, häviää.", p: 3, m: true, b: false, r: 2, k: 'kilpailu' },

    { id: 83, n: "Admin-huolto (Sankari)", d: "Sankarin on kerättävä seurueen kaikki tyhjät tölkit/lasit ja vietävä ne tiskille yksin.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'liikunta' },
    { id: 84, n: "Kiekon etsintä (Sankari)", d: "Sankari joutuu nousemaan ylös ja kävelemään baarin ympäri etsimässä 'kadonnutta kiekkoa'.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'liikunta' },
    { id: 85, n: "PUBG Emote (Sankari)", d: "Sankarin on esitettävä jokin PUBG-pelin tuuletus tai liike baarin keskellä mahdollisimman näyttävästi.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 86, n: "Koodin katselmointi (Sankari)", d: "Sankarin on keksittävä jokaisesta pelaajasta yksi positiivinen 'kommentti' (kuten koodin katselmoinnissa).", p: 1, m: 0, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 87, n: "Mise en place -tarkastus (Sankari)", d: "Sankarin on maistettava kolmen eri pelaajan juomaa ja arvattava niiden ainesosat.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'juoma' },
    { id: 88, n: "Ping-testi (Sankari)", d: "Sankarin on vastattava 'PONG' sekunnin sisällä aina kun joku huutaa 'PING' seuraavan 10 minuutin ajan.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 89, n: "Putti-haaste (Sankari)", d: "Sankarin on heitettävä lasinalunen pystyasennossa olevaan tyhjään tuoppiin. Kolme yritystä.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'liikunta' },
    { id: 90, n: "Blue Zone -juoksu (Sankari)", d: "Sankarin on käytävä koskettamassa baarin ulko-ovea ja palattava 15 sekunnissa takaisin.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'liikunta' },
    { id: 91, n: "Hardware Troubleshooting (Sankari)", d: "Sankarin on selitettävä jollekin pelaajalle tai tuntemattomalle asiakkaalle, miten frisbeegolfin pituusdraivi tai IT-tuki toimii.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 92, n: "Chef's Special (Sankari)", d: "Sankarin on loihdittava 'annos' eli koottava pöydän snacks-kulhosta näyttävä taideteos ja syötävä se.", p: 1, m: 0, b: true, r: 1, isHero: true, k: 'juoma' },
    { id: 93, n: "Palvelinhuoneen hämärä (Sankari)", d: "Sankarin on suoritettava seuraava tilauksensa tai keskustelunsa kuiskaamalla, kuin hän olisi salaisessa palvelinruumissa.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 94, n: "Range-treeni (Sankari)", d: "Sankarin on 'heitettävä' viisi erilaista frisbeegolf-kiekkoa ja selitettävä niiden lentoradat seurueelle.", p: 1, m: 0, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 95, n: "Loot-varkaus (Sankari)", d: "Sankarin on onnistuttava ottamaan yksi hörppy jonkun muun lasista niin, ettei kukaan huomaa (stealth mode).", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'juoma' },
    { id: 96, n: "Käyttöjärjestelmän vaihto (Sankari)", d: "Sankarin on vaihdettava kieltä ja puhuttava seuraavat 5 minuuttia pelkkää englantia.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 97, n: "Spotterin virhe (Sankari)", d: "Sankarin on osoitettava baarista kolme mahdollista 'vaaran paikkaa' ja annettava niille IT-tukihenkinen korjaussuunnitelma.", p: 1, m: 0, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 98, n: "C1-tason grippi (Sankari)", d: "Sankarin on pidettävä lasistaan kiinni erittäin oudolla otteella seuraavat 5 minuuttia.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'juoma' },
    { id: 99, n: "Bug Bounty (Sankari)", d: "Sankarin on etsittävä muiden pelaajien vaatetuksesta yksi 'bugi' ja kerrottava, miten se korjataan (esim. vino kaulus).", p: 1, m: 0, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 100, n: "Air Drop Defense (Sankari)", d: "Sankarin on suojeltava omaa juomaansa niin, ettei kukaan saa koskea siihen 5 minuuttiin.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'juoma' },
    { id: 101, n: "Mando-kierto (Sankari)", d: "Sankarin on noustava ylös ja kierrettävä koko seurue ympäri tehden samalla frisbeegolf-lähipeliä matkivia liikkeitä.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'liikunta' },
    { id: 102, n: "System Overload (Sankari)", d: "Sankarin on lueteltava 10 IT-termiä, 10 frisbeegolf-termiä tai 10 PUBG-termiä 30 sekunnissa.", p: 1, m: 1, b: true, r: 1, isHero: true, k: 'pokka' },
    { id: 132, n: "Ajoneuvo-spawn", d: "Siirry seuraavaan kohteeseen muulla tavalla kuin omin jaloin (esim. jonkun reppuselässä tai kottikärryissä).", p: 3, m: true, b: false, r: 2, k: 'liikunta' },
    { id: 133, n: "Access Denied", d: "Etsi ulkoa STOP-merkki ja ilmoita jollekin satunnaiselle ohikulkijalle vakavalla naamalla, että heidän tulee pysähtyä merkin kohdalla.", p: 3, m: true, b: false, r: 1, k: 'pokka' },
    { id: 134, n: "Äänikortin ajurivirhe", d: "Tilaa seuraava juomasi tiskiltä teeskentelemällä vakavaa ässä- ja ärrävikaa. Pokka ei saa pettää!", p: 3, m: true, b: false, r: 1, k: 'pokka' },
    { id: 135, n: "Touch Grass -protokolla", d: "Etsi ulkoa oikeaa nurmikkoa, kosketa ruohoa ja tee maassa kunnon ruohoenkeli.", p: 3, m: true, b: false, r: 2, k: 'liikunta' },
    { id: 136, n: "Phishing-hyökkäys", d: "Tilaa jollekin seurueen jäsenelle shotti vettä limelohkolla. Pyydä baarimikkoa viemään se ja kertomaan saajalle, että se oli sinulta.", p: 3, m: true, b: false, r: 1, k: 'juoma' },
    { id: 137, n: "Speedrun-tekniikka", d: "Nouse pöydästä ja Naruto-juokse (kädet suorana selän takana, yläkroppa etunojassa) baarin vessaan asti.", p: 3, m: true, b: false, r: 2, k: 'liikunta' },
    { id: 138, n: "Näytönsäästäjä-tila", d: "Vältä kaikkea katsekontaktia kenenkään ihmisen kanssa seuraavan 5 minuutin ajan. Jos katsot jotakuta vahingossakin silmiin, epäonnistut.", p: 2, m: true, b: false, r: 2, k: 'pokka' }
];
