window.allCards = [];

// ==========================================
// ELÄINTEN GRAFIIKAT JA KIROILEVAT SOLVAUKSET
// ==========================================
const doodleSVGs = [
    "M 30 70 Q 20 70 20 60 Q 30 20 60 20 Q 80 20 80 50 Q 80 70 70 70 Z M 25 50 L 15 40 M 35 35 L 25 20 M 50 25 L 50 10 M 65 30 L 75 15 M 75 45 L 90 40", 
    "M 30 70 L 30 40 L 20 20 L 40 30 L 60 30 L 80 20 L 70 40 L 70 70 Z M 20 50 L 10 45 M 20 55 L 10 55 M 80 50 L 90 45 M 80 55 L 90 55",
    "M 25 70 C 10 70 10 30 35 30 C 35 20 45 20 50 30 C 55 20 65 20 65 30 C 90 30 90 70 75 70 Z",
    "M 50 70 C 20 70 30 40 50 30 C 70 40 80 70 50 70 M 50 30 L 45 20 L 50 25 L 55 20 Z"
];

const insults = [
    "V*ttu mikä heitto, ootko sä koskaan edes pitänyt kiekkoa kädessä?",
    "P*rkele, mummonikin puttaa paremmin, ja se on ollut kuolleena 10 vuotta.",
    "S**tanan sirkkeli, puut tykkää susta enemmän ku sun omat vanhemmat.",
    "Ei h*lvetti, jopa Jeesus itkee ton sun tekniikan takia.",
    "P*ska veto. Sun draivi on lyhyempi ku mun kärsivällisyys.",
    "V*tun hieno lay-up! Ai se olikin sun maksimidraivi?",
    "Mene s**tana takas rangelle, tää on noloa meille kaikille.",
    "P*rkeleen rystykääntö, kiekko lensi enemmän taakse ku eteen.",
    "Miten sä v*ttu onnistut missaamaan 2 metristä?",
    "H*lvetin hieno puuosuma! Tähtäsitkö sä siihen vai ootko vaan p*ska?",
    "V*tun noloa. Caddiekin lähti äsken kotiin häpeästä.",
    "S**tanan kalliit kiekot, mut taidot on 0 euroa.",
    "P*rkele, sun rystyheitto näyttää siltä ku yrittäisit heittää pesukonetta.",
    "V*tun grippilokki! Ota se käsi irti siitä muovista ajoissa.",
    "P*ska putti, p*ska mies. Yksinkertaista.",
    "H*lvetti soikoon, sun kiekko etsii enemmän sieniä ku metsästäjät.",
    "V*ttu sulaa aivot ku joutuu kattoon tota sun räpellystä.",
    "S**tana mikä uikku, ootko harkinnu vaikka pitsinnypläystä?",
    "P*rkeleen amatööri, sun bägi painaa enemmän ku sun ÄO.",
    "V*tun hieno rolleri! Harmi vaan että se pysähty ekaan käpyyn.",
    "P*ska heitto! Edes myötätuuli ei halua auttaa sua.",
    "H*lvetin puunhakkaaja. Montako kuutiota teit polttopuuta tolla draivilla?",
    "V*ttu sä olet hidas! Heitä nyt s**tana!",
    "P*rkele, heitä silmät kii ens kerralla, ei se ainakaan huonommin voi mennä.",
    "V*tun kiva kattoa ku yrität. Et siis onnistu, mut yrität.",
    "S**tanan vässykkä, ota se putteri ja laita se sisään!",
    "P*ska formi! Sun x-step näyttää humalaisen ripaskalta.",
    "H*lvetti, mä voisin heittää vasemmalla kädellä paremmin ku sä.",
    "V*ttu mikä antsa, se käänsi suoraan naapurin takapihalle.",
    "P*rkeleen luuseri, älä syytä tuulta, syytä peiliä.",
    "S**tana, edes ammattilainen ei keksis tekosyytä tolle heitolle.",
    "V*tun hienot vaatteet, harmi ettei ne korjaa sun tekniikkaa.",
    "P*ska laji sulle. Oikeesti, lopeta ajoissa.",
    "H*lvetin tunari, sun kiekko lens melkein 10 metriä!",
    "V*ttu säästetään kaikkien aikaa ja merkkaa suoraan tuplabogey.",
    "P*rkeleen noloa. En halua edes seisoa sun lähellä tiillä.",
    "S**tana sun upsit tulee aina suoraan omaan päähän.",
    "V*tun turisti, lopeta se ranteella vemputtaminen.",
    "P*skat taidot. Ostit sitte Paul McBethin kiekon luullen et se auttaa?",
    "H*lvetti sä oot surkee. Voisitko mennä pelaan pallo-golfia?",
    "V*ttu sä heität kovaa! Harmi ettei se osu ikinä väylälle.",
    "P*rkeleen sokea kana, kori on tuolla päin!",
    "S**tanan räpyläkäsi, ote lipsuu pahemmin ku Suomen talous.",
    "V*tun väsyny suoritus. Ootko ollu ryyppäämässä vai ootko aina tollanen?",
    "P*ska heitto! Anna ku mä näytän miten tää laji toimii.",
    "H*lvetin puolisokea, etkö nää missä se kori oikein on?",
    "V*ttu sä oot huono! Miten ees fysiikka sallii tommosen heiton?",
    "P*rkele sun kämmen näyttää siltä ku oisit heittämässä kiveä mereen.",
    "S**tanan säälittävä yritys. Käy hakeen kiekkos ja häpee.",
    "V*tun itkijä, lopeta se valittaminen ja opettele heittään.",
    "P*ska putti! Laita se markkeri perseesees jos et muuta osaa.",
    "H*lvetti sentään, pitäiskö mun soittaa sulle opaskoira?",
    "V*ttu mikä hysse! Se meni niin korkeelle et lintu sai sydärin.",
    "P*rkeleen ränniheittäjä, ootko koskaan osunu ykkösväliin?",
    "S**tanan alarauta, aina sä kolistelet noita peltejä.",
    "V*tun hyvä lay-up 2 metristä. Ootko ylpeä?",
    "P*ska draivi, p*skemmat housut. Mee kotiin.",
    "H*lvetin surkimus, jopa mä häpeän sun puolesta.",
    "V*ttu sä et osaa! Lopeta se muovin paiskonta.",
    "P*rkele onks sulla kädessä joku asennusvirhe?",
    "S**tanan tyhmä veto. Miks helvetissä valitsit ton linjan?",
    "V*tun puusilmä, se kiekko löytyy varmaan toiselta mantereelta.",
    "P*skamainen keli, p*ska heittäjä. Täydellinen kombo.",
    "H*lvetti sä roiskit tota kiekkoa ku hullu koira.",
    "V*ttu sä oot naurettava. C1-putit ohi vasemmalta ja oikeelta.",
    "P*rkeleen sirkuspelle, heitä välillä normaalisti!",
    "S**tanan metkuttaja, koita edes pysyä pois OB:lta kerran.",
    "V*tun räkänen heitto, ei edes pyörinyt.",
    "P*ska peli, mut hei, oothan sä aina ollut tollanen.",
    "H*lvetin tunari, sun kiekko pelkää sua. Siks se karkaa puskaan.",
    "V*ttu mua itkettää sun puolesta.",
    "P*rkele miten sä voit olla noin p*ska joka kerta?",
    "S**tanan alisuorittaja, sä oot tän lajin häpeäpilkku.",
    "V*tun kädetön apina, ote irti kiekosta ajoissa!",
    "P*ska suoritus. Oisit ees jättäny draiverit kotiin.",
    "H*lvetin hyvä yritys. Ei ollu lähelläkään.",
    "V*ttu sun saatto on niin lyhyt et näyttää ku saisit sähköiskun.",
    "P*rkele mee plokkaan marjoja tonne metsään, kun kerran siellä oot.",
    "S**tanan harrastelija, kato YouTubesta vähän mallia.",
    "V*tun läpsyttelijä, heitä sitä kiekkoa äläkä silitä sitä.",
    "P*ska formi! Näyttää ku sorsalla ois ripuli.",
    "H*lvetti mä en kestä enää kattoo tota.",
    "V*ttu sun fore näyttää siltä et sulta lähtee käsi irti.",
    "P*rkele mikä roikku, ootko heittämässä vappupalloa?",
    "S**tanan narukäsi, eikö irtoa enempää tehoa?",
    "V*tun noloo. Sä oot syy miks lajia ei arvosteta.",
    "P*ska linja. Miten sä edes keksit heittää tosta?",
    "H*lvetin metsäpeikko, taasko sä olet siellä tiheikössä?",
    "V*ttu oot varmaan ylpeä tosta heitosta, vaikka se meni päin v*ttua.",
    "P*rkeleen sunnuntaipelaaja, sun peli on yhtä kärsimystä.",
    "S**tana ootko sä sokea vai vaan äärimmäisen tyhmä?",
    "V*tun hyvä! Eikun siis s**tanan p*ska.",
    "P*skaa! Silkkaa p*skaa koko sun kierros.",
    "H*lvetti sentään, en tiennyt et ihminen voi olla noin koordinaatiokyvytön.",
    "V*ttu sä oot pehmeä. Anna vähän runtua siihen heittoon!",
    "P*rkele sun tekniikalla ei pitäis antaa poistua kotoa.",
    "S**tanan epäonnistuja, laita kiekot myyntiin Toriin heti.",
    "V*tun hyvä pomppu! Harmi et se pomppas suoraan OB:lle.",
    "P*ska peli. Jos oisit koira, sut vietäis piikille tosta suorituksesta.",
    "H*lvetin vässykkä, puttaa se sisään äläkä pelkää!",
    "V*ttu sääli on sairautta, mut mä oikeesti säälin sua just nyt.",
    "P*rkele sä olet toivoton tapaus.",
    "S**tana laita se PDGA-numero piiloon tolla pelillä.",
    "V*tun lapanen, mihin sä sen oikein heitit?",
    "P*ska mies, p*skempi fore.",
    "H*lvetti mikä laiskanlinna, eikö yhtään kiinnosta yrittää?",
    "V*ttu mun aivot sulaa sun heittojen takia.",
    "P*rkeleen pullasorsa, lopeta se leipominen ja heitä!",
    "S**tanan säheltäjä, kiekko ei oo mikään frisbee-lelu rannalla.",
    "V*tun hieno tuplabogey! Sä oot tän radan kingi.",
    "P*ska veto! Pitäiskö sun kokeilla jotain helpompaa, niiku nukkumista?",
    "H*lvetti sä näytät ihan v*tun naurettavalta tiillä.",
    "V*ttu sä et osaa ees teipata sormia oikein.",
    "P*rkele mä häpeän olla samassa poolissa sun kanssa.",
    "S**tanan vinkuja, turpa kii ja heitä paremmin.",
    "V*tun idiootti, kiekossa on liidosta kyse, ei kaivamisesta.",
    "P*ska kiekko vai p*ska heittäjä? Mä tiedän vastauksen.",
    "H*lvetin raivostuttavaa kattoa sun putteja.",
    "V*ttu sun grip-lock on legendaarinen, päin v*ttua joka kerta.",
    "P*rkele sun svingi on niiku ruosteinen portti.",
    "S**tanan pösilö, taasko kiekko meni veteen?",
    "V*tun itkupilli, eihän se oo ku muovia metsässä.",
    "P*ska peli, ootko aatellu et frisbeegolf ei vaan oo sua varten?",
    "H*lvetti mä heittäisin sut perässä sinne järveen.",
    "V*ttu sä oot sysip*ska. Ei voi muuta sanoa.",
    "P*rkeleen velttoilija, missä sun asenne on?",
    "S**tana sun avaukset on lyhyempiä ku mun putit.",
    "V*tun munapää, älä ota tuurista kunniaa itelles.",
    "P*skan marjat, et sä tota yrittänyt hakea.",
    "H*lvetin aivokuollut linjavalinta.",
    "V*ttu sä teet mut fyysisesti sairaaks tolla formilla.",
    "P*rkele laita silmät auki kun heität!",
    "S**tanan sähläri, ei tää oo rakettitiedettä.",
    "V*tun p*ska. Anna kiekot mulle ja painu v*ttuun täältä.",
    "P*ska sää, p*ska rata, mut sä oot p*skin kaikista.",
    "H*lvetti ootko sä liimannu sen kiekon kiinni käteens?",
    "V*ttu mikä nyssykkä. Edes vauva ei heitä noin hiljaa.",
    "P*rkeleen surkimus, toi oli säälittävin heitto mitä oon ikinä nähny.",
    "S**tanan noloa. Älä kerro kellekään et tunnet mut.",
    "V*tun idiootti, luitko sä tuulen ihan tarkotuksella väärin?",
    "P*ska peli. Jos tyhmyydestä sais miinuksia, oisit radan ennätysmies.",
    "H*lvetti sä tuhoat mun elämänhalun tolla pelillä.",
    "V*ttu ota ittees niskasta kii ja lopeta toi s**tanan sähläys!",
    "P*rkele sä olet friban musta aukko, imeet kaiken ilon lajista.",
    "S**tana mun isoäiti on rollaattorissa ja voittais sut yhdellä kädellä.",
    "V*tun p*ska, sun draivi muistuttaa mua oksennuksesta: molemmat tulee yllättäen ja menee päin h*lvettiä.",
    "P*ska putti. Ja p*skat on sun housuissakin.",
    "H*lvetti sun rysty on v*tun surullinen näky."
];

// ==========================================
// TASO 1: PIENET SABOTAASIT (Aidosti vaikuttavat, ei turhia leikkejä)
// ==========================================
const minorBases = [
    { n: "Heikompi käsi (Putti)", d: "Kohteen on suoritettava kaikki alle 10m putit heikommalla kädellään tällä väylällä." },
    { n: "Paikaltaveto", d: "Seuraavassa heitössä kohde ei saa ottaa yhtään vauhtiaskelta." },
    { n: "Haaraseisonta", d: "Seuraava heitto on suoritettava pakollisesta ja staattisesta haaraseisonnasta." },
    { n: "Polvelta", d: "Seuraava heitto on suoritettava siten, että vähintään toinen polvi on maassa irrotushetkellä." },
    { n: "Kurki-asento", d: "Heiton irrotushetkellä vain yksi jalka saa koskea maahan." },
    { n: "Kiekon rajoitus", d: "Määrää yksi kiekko kohteen bägistä, jota hän ei saa käyttää seuraavaan heittoon." },
    { n: "Pakollinen Hysse", d: "Seuraavan heiton on oltava selkeä hyzer. Jos kiekko kääntää yli, +1 rangaistus." },
    { n: "Pakollinen Antsa", d: "Seuraavan heiton on lähdettävä selkeässä anhyzer-kulmassa." },
    { n: "Fore-lähestyminen", d: "Kohteen seuraava heitto (pl. avaus) on heitettävä kämmenellä (fore)." },
    { n: "Rysty-lähestyminen", d: "Kohteen seuraava heitto (pl. avaus) on heitettävä rystyllä." },
    { n: "Ei ristiaskelta", d: "Vauhdinotossa ei saa käyttää ristiaskelta (x-step)." },
    { n: "Putteriavaus", d: "Avausheitto tiiltä on pakko suorittaa putterilla." },
    { n: "Midariavaus", d: "Avausheitto tiiltä on pakko suorittaa midrange-kiekolla." },
    { n: "Pikaveto (10s)", d: "Kohteella on maksimissaan 10 sekuntia aikaa heittää saavuttuaan markkerille." },
    { n: "Selin koriin irrotus", d: "Heiton irrotushetkellä kohteen rintamasuunnan on oltava poispäin korista." },
    { n: "Spontaani (5s)", d: "Kohteen on irrotettava kiekko 5 sekunnin sisällä oman vuoronsa alkamisesta." },
    { n: "Kevyt kiekko", d: "Kohteen on valittava bägistään kevyin/alivakain kiekkonsa seuraavaan heittoon." },
    { n: "Painava kiekko", d: "Kohteen on valittava bägistään vakain tai painavin kiekkonsa seuraavaan heittoon." },
    { n: "Ei saattoa", d: "Heittokäden on pysähdyttävä kuin seinään heti irrotuksen jälkeen." },
    { n: "Putti haaralta", d: "Kaikki putit tällä väylällä on pakko suorittaa haaraputtina." }
];
minorBases.forEach((base, i) => window.allCards.push({ id: "minor_" + i, n: base.n, d: base.d, tier: "normal", type: "minor_sabotage" }));

// ==========================================
// TASO 2: ISOT SABOTAASIT (Muuttavat fysiikkaa radikaalisti)
// diff 1 = Helppo (3 P), diff 2 = Vaikea (5 P), diff 3 = Erittäin vaikea (8 P)
// ==========================================
const majorBases = [
    { n: "Heikompi käsi (Avaus)", d: "Avausheitto tiiltä on heitettävä heikommalla kädellä.", diff: 3 },
    { n: "Rolleri-pakko", d: "Seuraavan heiton on osuttava maahan ja rullattava eteenpäin vähintään 10m.", diff: 3 },
    { n: "Upsi / Tomahawk", d: "Seuraava heitto on suoritettava pystyheitolla (Upsi/Tomahawk/Thumber).", diff: 2 },
    { n: "Turbo-putti", d: "Seuraava putti on suoritettava sormilla kiekon alta työntäen (Turbo).", diff: 2 },
    { n: "Scooberi", d: "Suorita lähestymisheitto ylösalaisella scuuberi-tyylillä.", diff: 3 },
    { n: "Vain 1 kiekko (Väylä)", d: "Kohde joutuu pelaamaan tämän väylän loppuun asti vain yhdellä valitsemallasi kiekolla.", diff: 2 },
    { n: "Silmät kiinni putti", d: "Kaikki alle 10 metrin putit on suoritettava silmät tiukasti kiinni.", diff: 3 },
    { n: "Vastakierre", d: "Kiekon on lähdettävä kädestä siten, että se pyörii väärään suuntaan (esim. rysty ilman rannetta).", diff: 3 },
    { n: "Kämmen-rolleri", d: "Seuraava heitto on suoritettava kämmen-rollerina (fore-roller).", diff: 3 },
    { n: "Draiveriputti", d: "Kaikki putit tällä väylällä on suoritettava nopeimmalla pituusdraiverilla.", diff: 1 },
    { n: "Istualtaan heitto", d: "Seuraava heitto on pakko heittää maassa istuen (pylly kiinni maassa).", diff: 3 },
    { n: "Aliheitto", d: "Heitto on suoritettava roikkuvana alakauttaheilautuksena.", diff: 3 },
    { n: "Väärä jalka tukena", d: "Tukijalkana markkerin takana on käytettävä väärää jalkaa (oikeakätisellä oikea jalka takana).", diff: 2 },
    { n: "Ei draivereita", d: "Kohde ei saa käyttää nopeampia kiekkoja kuin nopeusluokka 5 tällä väylällä.", diff: 1 },
    { n: "Kiekon pakkovalinta", d: "Valitse kohteen bägistä 1 kiekko, jolla hänen on pakko suorittaa avaus.", diff: 2 }
];
majorBases.forEach((base, i) => {
    let diffStars = "⭐".repeat(base.diff);
    window.allCards.push({ id: "major_" + i, n: base.n, d: `[Vaikeus: ${diffStars}] ${base.d}`, tier: "normal", type: "major_sabotage", diff: base.diff });
});

// ==========================================
// TASO 1: PERUS HELPOTUKSET (Buffit, Ei pelirajoitusta)
// ==========================================
const buffBases = [
    { n: "Mulligan", d: "Voit uusia oman epäonnistuneen heittosi." },
    { n: "Mulligan (Putti)", d: "Voit uusia epäonnistuneen putin (alle 10m)." },
    { n: "Mulligan (Avaus)", d: "Voit uusia epäonnistuneen avausheiton tiiltä." },
    { n: "Siirto +2m", d: "Voit siirtää kiekkoasi 2 metriä mihin tahansa suuntaan (ei lähemmäs koria)." },
    { n: "Siirto +5m", d: "Voit siirtää kiekkoasi 5 metriä mihin tahansa suuntaan (ei lähemmäs koria)." },
    { n: "Kumous", d: "Peruuta sinuun juuri kohdistettu 1-tason (pieni) sabotaasi." },
    { n: "Vahva Kumous", d: "Peruuta sinuun kohdistettu 2-tason (iso) sabotaasi." },
    { n: "Peilaus", d: "Jos joku pelaa sinuun sabotaasin, voit kääntää sen välittömästi takaisin häneen itseensä." },
    { n: "Puskasta pois", d: "Saat siirtää kiekkosi vapaasti pelattavalle väylälle samalle etäisyydelle korista." },
    { n: "Varaslähtö", d: "Saat heittää 2 avausheittoa tiiltä ja jatkaa niistä vapaasti paremmalla." },
    { n: "Mando-ohitus", d: "Jos väylällä on mando, saat jättää sen huomioimatta ilman rangaistusta." },
    { n: "OB-pelastus", d: "Jos heitit Out of Bounds (OB), saat jatkaa heittopaikalta ilman rangaistusheittoa." },
    { n: "Oksan poisto", d: "Kuvitteellinen oksasaha: Saat jättää huomioimatta yhden edessä olevan oksan tai pensaan (siirrä kiekkoa hieman sivuun)." },
    { n: "Turvamies", d: "Suojaa sinut kaikilta sabotaaseilta koko tämän väylän ajan. Pelattava ennen avausheittoa." },
    { n: "Lähinnä koria", d: "Jos olet lähimpänä koria avauksen jälkeen (CTP), saat +1 pelirahaa kassaan." },
    { n: "Tuplavoitto", d: "Jos voitat tämän väylän (yksin tai jaettuna), saat x2 väylävoiton pisteet!", mech: "double_win" },
    { n: "Tuplatehtävä", d: "Jos voitat väylätehtävän, saat siitä tuplamäärän (x2) rahaa automaattisesti.", mech: "double_task" },
    { n: "Korttituho", d: "Tuhoa yksi satunnainen kortti valitsemasi vastustajan kädestä (Ei vie varoja)." },
    { n: "Pankkiiri", d: "Saat ottaa pankista yhden satunnaisen 1-tason (pienen) sabotaasin itsellesi ilmaiseksi." },
    { n: "Tiipaikan vaihto", d: "Saat heittää avauksesi mistä tahansa kohtaa tiipadiltä tai sen sivusta (max 2m säteellä)." },
    { n: "Taikamarkkeri", d: "Saat asettaa markkerisi ETEENPÄIN (tasan 1 metri lähemmäs koria)." },
    { n: "Kilpi", d: "Aktivoituu heti kun se pelataan. Seuraava sinuun kohdistuva sabotaasi mitätöityy automaattisesti." },
    { n: "Kiekon lainaus", d: "Voit ottaa yhden vastustajan kiekon omaan käyttöösi tälle väylälle." },
    { n: "Ketjuralli", d: "Jos putti osuu ketjuihin mutta sylkee ulos, se lasketaan sisään menneeksi." },
    { n: "Riskitön", d: "Jos heität seuraavan heittosi vesiesteeseen tai pahasti puskaan, saat heittää sen rangaistuksetta uudelleen." },
    { n: "Ei sääntöjä", d: "Voit astua markkerin yli heti irrotuksen jälkeen, vaikka olisit alle 10m ringissä." },
    { n: "Parantaja", d: "Poista valitsemaltasi pelaajalta yksi rangaistusheitto tuloskortista (voi käyttää myös itseensä)." },
    { n: "Suunta on oikea", d: "Jos heitto lähtee täysin väärään suuntaan (yli 45 astetta tavoitteesta), saat uusia sen ilmaiseksi." },
    { n: "Ketjuklinikka", d: "Jos osut rautoihin (ala/ylä) mutta et ketjuihin, saat uusia putin." },
    { n: "Helpotettu väylä", d: "Jos väylällä on OB, koko väylä pelataan ilman OB-sääntöjä (ei rangaistusta)." }
];
buffBases.forEach((base, i) => window.allCards.push({ id: "buff_" + i, n: base.n, d: base.d, tier: "normal", type: "buff", mech: base.mech || null }));

// ==========================================
// TASO 3: KAUPAN MONSTERIKORTIT (Premium)
// ==========================================
const monsterBases = [
    { n: "Köyhyyskirous", d: "Kohde ei saa ollenkaan passiivista tuloa tältä väylältä.", type: "major_sabotage", price: 12, mech: "deny_passive" },
    { n: "Veromätky", d: "KAIKKI vastustajat menettävät passiivisen tulonsa tältä väylältä.", type: "major_sabotage", price: 20, aoe: true, mech: "deny_passive" },
    { n: "Palkkion eväys", d: "Kohde ei saa väylävoiton pisteitä, vaikka hän voittaisi tämän väylän.", type: "major_sabotage", price: 15, mech: "deny_win" },
    { n: "Täystuho", d: "Määrää yksi Iso Sabotaasi (Taso 2) täysin itse keksimilläsi säännöillä kohteelle.", type: "major_sabotage", price: 20 },
    { n: "OB-Magneetti", d: "Valitse kohde. Jos hän menee OB:lle tällä väylällä, hän saa +2 rangaistusheittoa normaalin +1 sijaan.", type: "major_sabotage", price: 18 },
    { n: "Pankin Tuki", d: "Saat pankista välittömästi uuden rahoituksen (+8 P).", type: "buff", price: 12 }, 
    { n: "Kiekkolukko", d: "Kiellä kohdetta käyttämästä hänen luottodraiveriaan koko loppukierroksen ajan.", type: "major_sabotage", price: 25 },
    { n: "Laser-Tähtäin", d: "Voit siirtää mitä tahansa alle 20m puttiasi 5 metriä lähemmäs koria.", type: "buff", price: 15 },
    { n: "Vaihtokauppa", d: "Vaihda huono avausheittosi paikkaa kohteen hyvän avauksen kanssa.", type: "major_sabotage", price: 25 },
    { n: "Jumal-Kumous", d: "Pelaa tämä peruuttaaksesi MIKÄ TAHANSA sabotaasi (myös monsteri).", type: "buff", price: 18 },
    { n: "Par-Varmistus", d: "Heitä normaalisti. Tuloskorttiisi merkitään automaattisesti enintään PAR (Vaikka heittäisit 10).", type: "buff", price: 22, mech: "force_par" },
    { n: "Korttijäädytys", d: "Kohde ei saa pelata yhtäkään korttia kädestään seuraavien 3 väylän aikana.", type: "major_sabotage", price: 20 },
    { n: "Ukkosmyrsky", d: "KAIKKI vastustajat heittävät avauksensa väärällä kädellä tällä väylällä.", type: "major_sabotage", price: 30, aoe: true },
    { n: "Haamukiekko", d: "Koko loppukierroksen ajan, kerran väylässä saat peruuttaa yhden heittosi ilmaiseksi.", type: "buff", price: 35 },
    { n: "Korttikato", d: "Kohde ei saa nostaa uusia kortteja tämän väylän tulosten jaon yhteydessä.", type: "major_sabotage", price: 18, mech: "deny_draw" },
    { n: "Magneettikori", d: "Seuraava putti alle 15m lasketaan aina sisään menneeksi, osuipahan se tai ei.", type: "buff", price: 20 }
];
monsterBases.forEach((base, i) => window.allCards.push({ id: "monster_" + i, n: `${base.n}`, d: base.d, tier: "premium", type: base.type, price: base.price, aoe: base.aoe || false, mech: base.mech || null }));

// ==========================================
// VÄYLÄSÄÄNNÖT (Koko porukan tehtävät & säännöt)
// Nämäkin on viilattu enemmän mekaniikkaan perustuviksi
// ==========================================
window.holeRules = [
    { type: "rule", n: "Putteri-Ruletti", d: "Koko väylä pelataan pelkillä puttereilla. Muut kiekot kielletty." },
    { type: "rule", n: "Kämmenväylä", d: "Kaikki yli 10 metrin lähestymiset ja avaukset on pakko heittää kämmeneltä (forehand)." },
    { type: "rule", n: "Rystyn kielto", d: "Rystyheitot ovat täysin kiellettyjä tällä väylällä." },
    { type: "rule", n: "Heikompi käsi avaus", d: "Kaikkien on suoritettava avausheitto heikommalla kädellään." },
    { type: "rule", n: "Yhden kiekon taktiikka", d: "Jokaisen on valittava vain YKSI kiekko, jolla pelataan väylä alusta loppuun." },
    { type: "rule", n: "Rolleriavaus", d: "Kaikkien on pakko yrittää roller-avausta tiiltä." },
    { type: "rule", n: "Midari-Only", d: "Väylä on pakko pelata vain ja ainoastaan midareilla." },
    { type: "rule", n: "Aina haaraseisonta", d: "Kaikki heitot (myös avaus) on heitettävä paikaltaan haaraseisonnasta." },
    { type: "rule", n: "Upsi-avaus", d: "Kaikkien pelaajien on pakko avata tiiltä pystyheitolla (Upsi tai Thumber)." },
    { type: "rule", n: "Speed Golf", d: "Tätä väylää ei mietitä. Jokaisella on vain 5 sekuntia aikaa heittää omalla vuorollaan." },
    { type: "rule", n: "Väärä liikerata", d: "Kaikki vauhdinotto tapahtuu peruuttaen tiille päin." },
    { type: "rule", n: "Fore-putti", d: "Kaikki putit tällä väylällä on suoritettava kämmenellä (fore)." },
    { type: "rule", n: "Ei hyppyputteja", d: "Kaikki hyppy- tai steppiputit on kielletty tällä väylällä." },
    { type: "rule", n: "Kyykkyputti", d: "Kaikki C1 (10m) sisällä olevat putit on heitettävä syvästä kyykystä." },
    { type: "rule", n: "Pitkä saatto", d: "Käden on osoitettava koria kohti 3 sekuntia irrotuksen jälkeen." },
    { type: "bounty", n: "CTP-Kisa", d: "Tiiltä lähimmäksi koria osunut avaus voittaa väylätehtävän." },
    { type: "bounty", n: "Pitkä Putti", d: "Väylän pisimmän onnistuneen putin tekijä voittaa väylätehtävän." },
    { type: "bounty", n: "Pelastaja", d: "Ensimmäinen pelaaja, joka menee ryteikköön tai OB:lle, mutta pelastaa silti Par-tuloksen, voittaa tehtävän." },
    { type: "bounty", n: "Puu-Kuningas", d: "Se pelaaja, joka osuu eniten puihin tällä väylällä mutta EI saa eniten heittoja, voittaa tehtävän." },
    { type: "bounty", n: "Ensimmäinen rauta", d: "Ensimmäinen pelaaja joka puttaa alarautaan tai ylärautaan (ei sisään), voittaa tehtävän." },
    { type: "bounty", n: "Parkkeeraus", d: "Se pelaaja, jonka avaus jää alle 2 metrin päähän korista, voittaa tehtävän." },
    { type: "bounty", n: "Ei sirkkeliä", d: "Pelaaja, joka selviää koko väylän osumatta kertaakaan puuhun, voittaa tehtävän." },
    { type: "bounty", n: "Bullseye Putti", d: "Ensimmäinen, joka upottaa putin yli 10 metrin (C1) rajalta, voittaa tehtävän." },
    { type: "bounty", n: "Nosto", d: "Se pelaaja, jolla on lyhyin putti ('nosto') jäljellä, voittaa tehtävän." },
    { type: "bounty", n: "Birdie-jahti", d: "Kaikki ketkä tekevät tällä väylällä Birdien (alle parin), voittavat tehtävän." },
    { type: "bounty", n: "Bogey-Vapaa", d: "Kaikki jotka pelaavat väylän ilman Bogeya (yli par), jakavat tehtävän voiton." },
    { type: "bounty", n: "Nopein heittäjä", d: "Se pelaaja, joka pelaa oman vuoronsa poikkeuksetta nopeimmin (ilman viivyttelyä), voittaa tehtävän." },
    { type: "bounty", n: "Sweet Spot", d: "Kuka pääsee avauksella parhaaseen 'sweet spottiin' (pelattavimpaan paikkaan), voittaa tehtävän." },
    { type: "bounty", n: "Riskinottaja", d: "Se, joka yrittää rohkeinta ja vaikeinta linjaa (onnistui tai ei), voittaa tehtävän (ryhmä äänestää)." }
];
